spring:
  application:
    name: ms-discovery
server:
  port: 8761 

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # Como es un servidor no nos registramos con eureka, porque nosotros somos el servidor
    fetch-registry: false # False porque es servidor
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  